class Autogenerated {
  late List<Items> items;
  late Meta meta;

  Autogenerated({required this.items, required this.meta});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['items'] != null) {
      items = <Items>[];
      json['items'].forEach((v) {
        items.add(new Items.fromJson(v));
      });
    }
    meta = (json['meta'] != null ? new Meta.fromJson(json['meta']) : null)!;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.items != null) {
      data['items'] = this.items.map((v) => v.toJson()).toList();
    }
    if (this.meta != null) {
      data['meta'] = this.meta.toJson();
    }
    return data;
  }
}

class Items {
  late int id;
  late String receita;
  late String ingredientes;
  late String modoPreparo;
  late String linkImagem;
  late String tipo;
  late String createdAt;
  late List<IngredientesBase> ingredientesBase;

  Items(
      {required this.id,
      required this.receita,
      required this.ingredientes,
      required this.modoPreparo,
      required this.linkImagem,
      required this.tipo,
      required this.createdAt,
      required this.ingredientesBase});

  Items.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    receita = json['receita'];
    ingredientes = json['ingredientes'];
    modoPreparo = json['modo_preparo'];
    linkImagem = json['link_imagem'];
    tipo = json['tipo'];
    createdAt = json['created_at'];
    if (json['IngredientesBase'] != null) {
      ingredientesBase = <IngredientesBase>[];
      json['IngredientesBase'].forEach((v) {
        ingredientesBase.add(new IngredientesBase.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['receita'] = this.receita;
    data['ingredientes'] = this.ingredientes;
    data['modo_preparo'] = this.modoPreparo;
    data['link_imagem'] = this.linkImagem;
    data['tipo'] = this.tipo;
    data['created_at'] = this.createdAt;
    if (this.ingredientesBase != null) {
      data['IngredientesBase'] =
          this.ingredientesBase.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class IngredientesBase {
  late int id;
  late List<String> nomesIngrediente;
  late int receitaId;
  late String createdAt;

  IngredientesBase(
      {required this.id,
      required this.nomesIngrediente,
      required this.receitaId,
      required this.createdAt});

  IngredientesBase.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    nomesIngrediente = json['nomesIngrediente'].cast<String>();
    receitaId = json['receita_id'];
    createdAt = json['created_at'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['nomesIngrediente'] = this.nomesIngrediente;
    data['receita_id'] = this.receitaId;
    data['created_at'] = this.createdAt;
    return data;
  }
}

class Meta {
  late int itemCount;
  late int totalItems;
  late int itemsPerPage;
  late int totalPages;
  late int currentPage;

  Meta(
      {required this.itemCount,
      required this.totalItems,
      required this.itemsPerPage,
      required this.totalPages,
      required this.currentPage});

  Meta.fromJson(Map<String, dynamic> json) {
    itemCount = json['itemCount'];
    totalItems = json['totalItems'];
    itemsPerPage = json['itemsPerPage'];
    totalPages = json['totalPages'];
    currentPage = json['currentPage'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['itemCount'] = this.itemCount;
    data['totalItems'] = this.totalItems;
    data['itemsPerPage'] = this.itemsPerPage;
    data['totalPages'] = this.totalPages;
    data['currentPage'] = this.currentPage;
    return data;
  }
}
